/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.TrabalhoPratico;

import java.applet.Applet;
import java.applet.AudioClip;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author gin
 */
public class AudioClipDemo extends javax.swing.JFrame {

    //https://docs.oracle.com/javase/8/docs/api/index.html?java/applet/AudioClip.html
    //https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/AudioSystem.html
    
    //private AudioClip ac;
    private AudioInputStream input;
    private Clip ac;
    private long startPoint;
    private boolean isPlaying;
    
    /**
     * Creates new form AudioClipDemo
     */
    public AudioClipDemo() {
        
        initComponents();

        startPoint = 0;
        isPlaying = false;

        try {
            input = AudioSystem.getAudioInputStream(getClass().getResource("audio.wav").toURI().toURL());


            AudioFormat format = input.getFormat();

            DataLine.Info info = new DataLine.Info(Clip.class, format);

            //ac = AudioSystem.getClip();
            ac = (Clip)AudioSystem.getLine(info);
            ac.open(input);

        } catch (UnsupportedAudioFileException ex) {
        Logger.getLogger(AudioClipDemo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
        Logger.getLogger(AudioClipDemo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
        Logger.getLogger(AudioClipDemo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
        Logger.getLogger(AudioClipDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
        //ac = Applet.newAudioClip(getClass().getResource("audio.wav"));    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifms/TrabalhoPratico/icons8-reproduzir-youtube-64.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifms/TrabalhoPratico/icons8-pausa-circular-64.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifms/TrabalhoPratico/icons8-cancelar-64.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ac.play();
        
        //AudioInputStream
        ac.setMicrosecondPosition(startPoint);
        ac.start();
        
        
        System.out.println("tempo: "+ ac.getMicrosecondPosition());
        
        isPlaying = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //AudioInputStream
        if(isPlaying){
            startPoint = ac.getMicrosecondPosition();
            ac.stop();
        }
        else{
            ac.setMicrosecondPosition(startPoint);
            ac.start();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ac.stop();
        
        
        
        
        
        
       
        
        
        
        
        
        startPoint = 0;
        
        isPlaying = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudioClipDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudioClipDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudioClipDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudioClipDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudioClipDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
